name: pypsps Deployment
on:
  # Added manual trigger due to GH outages making jobs not start off automatically.
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.10.9

jobs:
  pre-check:
    name: Get Package Version
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.6.1
      - name: Get package version
        id: get-version
        run: echo "LATEST_VERSION=$(poetry version --short)" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.get-version.outputs.LATEST_VERSION }}
    
  publish-package:
    runs-on: ubuntu-latest
    needs: [pre-check]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: EvolutionIQ/devops/.github/actions/poetry-package-publishing@main
        id: package-version
        with:
          python_version: ${{ env.PYTHON_VERSION }}

  create-release:
    runs-on: ubuntu-latest
    needs: [pre-check, publish-package]
    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: EvolutionIQ/devops/.github/actions/create-release@main
        with:
          gh_bot_token: "${{ secrets.GH_BOT_TOKEN }}"
          package_version: ${{ needs.pre-check.outputs.version }}