name: pypsps
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  python-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: EvolutionIQ/devops/.github/actions/python-checks@main
        with:
          use_bot_ssh_key: true
          git_bot_ssh_key: ${{ secrets.GIT_BOT_SSH_KEY }}

  poetry-versioning:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
        - uses: EvolutionIQ/devops/.github/actions/poetry-package-versioning@main
          with:
            pull_request_head_ref: ${{ github.event.pull_request.head.ref }}
            pull_request_title: ${{ github.event.pull_request.title }}
            gh_bot_token: ${{ secrets.GH_BOT_TOKEN }}