name: pypsps CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  poetry-versioning:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
        - uses: EvolutionIQ/devops/.github/actions/poetry-package-versioning@main
          with:
            pull_request_head_ref: ${{ github.event.pull_request.head.ref }}
            pull_request_title: ${{ github.event.pull_request.title }}
            gh_bot_token: ${{ secrets.GH_BOT_TOKEN }}